### ISSUE TITLE
TypeScript definition generator can't correctly parse escaped brackets

### ISSUE THREAD

**Issue by pan93412** [napi-rs/napi-rs#1033]
## Brief Description

`napi build --platform --release` will throw `Syntax Error: Unexpected token [ in JSON at position 56` when parsing this:

```rust
/// \[napi-rs\] The engine uses to resolve audio.
#[napi]
pub enum Engine {
    /// Bilibili Music.
    Bilibili,
    /// Unoffical Netease Cloud Music API
    PyNCM,
    /// YouTube with `yt-dlp`.
    YtDlp,
    /// YouTube with `youtube-dl`.
    YtDl,
}
```

## Full Error Message

```
Syntax Error: Unexpected token [ in JSON at position 56
    at JSON.parse (<anonymous>)
    at /Users/pan93412/Projects/unm-rs/unm_resolver_napi/node_modules/@napi-rs/cli/scripts/index.js:12956:25
    at Array.map (<anonymous>)
    at /Users/pan93412/Projects/unm-rs/unm_resolver_napi/node_modules/@napi-rs/cli/scripts/index.js:12954:31
    at Generator.next (<anonymous>)
    at fulfilled (/Users/pan93412/Projects/unm-rs/unm_resolver_napi/node_modules/@napi-rs/cli/scripts/index.js:1675:58)
```

## `type_def` line

```
{"kind": "enum", "name": "Engine", "js_doc": "/**\u0020\[napi-rs\]\u0020The\u0020engine\u0020uses\u0020to\u0020resolve\u0020audio.\u0020*/\n", "def": "/**\u0020Bilibili\u0020Music.\u0020*/\nBilibili\u0020=\u00200,\n\u0020/**\u0020Unoffical\u0020Netease\u0020Cloud\u0020Music\u0020API\u0020*/\nPyNCM\u0020=\u00201,\n\u0020/**\u0020YouTube\u0020with\u0020`yt-dlp`.\u0020*/\nYtDlp\u0020=\u00202,\n\u0020/**\u0020YouTube\u0020with\u0020`youtube-dl`.\u0020*/\nYtDl\u0020=\u00203", "original_name": "Engine"}
```

## `package.json`

```
{
  "name": "unm_resolver_napi",
  "version": "0.0.0",
  "main": "index.js",
  "types": "index.d.ts",
  "napi": {
    "name": "unm_resolver_napi",
    "triples": {
      "additional": [
        "aarch64-apple-darwin",
        "aarch64-linux-android",
        "aarch64-unknown-linux-gnu",
        "aarch64-pc-windows-msvc",
        "x86_64-unknown-linux-musl"
      ]
    }
  },
  "license": "MIT",
  "devDependencies": {
    "@napi-rs/cli": "^2.4.0"
  },
  "engines": {
    "node": ">= 10"
  },
  "scripts": {
    "artifacts": "napi artifacts",
    "build": "napi build --platform --release",
    "build:debug": "napi build --platform",
    "prepublishOnly": "napi prepublish -t npm",
    "version": "napi version"
  }
}
```

## `yarn.lock`

```
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@napi-rs/cli@^2.4.0":
  version "2.4.0"
  resolved "https://registry.yarnpkg.com/@napi-rs/cli/-/cli-2.4.0.tgz#a74d991e12871d6fb8eb32b33cc53a9c105b1921"
  integrity sha512-rq4ivqWY7KWG104gRxTmWyehE4eUxJ/mBJx81r3PeghtLZ11NpJNuvF9kSvsol8hTjJQ7CWlF2plQ20I9rMOng==
```

**Comment by timfish** [comment]
I added this code so I'll take a look!
