### ISSUE TITLE
napi prepublish 报错

### ISSUE THREAD

**Issue by ChinaMars521** [napi-rs/napi-rs#1103]
Cannot read properties of undefined (reading 'split')
    at PrePublishCommand.<anonymous> (/usr/local/lib/node_modules/@napi-rs/cli/scripts/index.js:135601:65)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/@napi-rs/cli/scripts/index.js:3454:58)

**Comment by ChinaMars521** [comment]
线上编译报错

**Comment by ChinaMars521** [comment]
0.1.3

2022-03-18T09:25:21.921Z napi:prepublish Github repository: ChinaMars521/wtapi
Type Error: No release commit found with @wtapi_get/wtapi, original commit info: 0.1.3
    at PrePublishCommand.<anonymous> (/home/runner/work/wtapi/wtapi/node_modules/@napi-rs/cli/scripts/index.js:135615:27)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/wtapi/wtapi/node_modules/@napi-rs/cli/scripts/index.js:[34](https://github.com/ChinaMars521/wtapi/runs/5598221447?check_suite_focus=true#step:9:34)54:58)
npm ERR! code 1
npm ERR! path /home/runner/work/wtapi/wtapi
npm ERR! command failed
npm ERR! command sh -c napi prepublish

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-03-18T09_25_21_[40](https://github.com/ChinaMars521/wtapi/runs/5598221447?check_suite_focus=true#step:9:40)1Z-debug-0.log
Error: Process completed with exit code 1.

**Comment by ChinaMars521** [comment]
第一个是预编报错加上-c 也是一样 配置git 也是一样

**Comment by Brooooooklyn** [comment]
按照 https://napi.rs/docs/introduction/simple-package 文档一步步进行操作，不要随意操作然后报错了过来贴 issue。

**Comment by ChinaMars521** [comment]
不意思解决了，现在出现的问题是我添加了一个新的系统版本但是自动化上传不到npm
