### ISSUE TITLE
How to build the window(x64) 's .node on MacOS(M1)

### ISSUE THREAD

**Issue by l3ve** [napi-rs/napi-rs#1180]
How to build the window(x64) 's .node on MacOS(M1)

some config like below:

<img width="910" alt="image" src="https://user-images.githubusercontent.com/6791916/168269137-565d9e11-4ab7-433d-b168-2f0a16eeaefe.png">

<img width="316" alt="image" src="https://user-images.githubusercontent.com/6791916/168269368-c9c47ec4-8b1f-4832-995b-7f255f364da9.png">

``` cmd
yarn build::x64
yarn run v1.22.18
$ napi build --dts ./addons/function_tool.d.ts --js false --release --platform --target x86_64-pc-windows-gnu
   Compiling rust4node v0.1.0 (/Users/sansan/tuya/rust4node)
error: linking with `x86_64-w64-mingw32-gcc` failed: exit status: 1
  |
  = note: "x86_64-w64-mingw32-gcc" "-Wl,/var/folders/6z/p6995qm16g7dbz_29rqbccph0000gn/T/rustcr4ilcs/list.def" "-fno-use-linker-plugin" "-Wl,--dynamicbase" "-Wl,--disable-auto-image-base" "-m64" "-Wl,--high-entropy-va" "/Users/sansan/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/x86_64-pc-windows-gnu/lib/rsbegin.o" "/Users/sansan/tuya/rust4node/target/x86_64-pc-windows-gnu/release/deps/rust4node.rust4node.26becb8e-cgu.1.rcgu.o" "-L" "/Users/sansan/tuya/rust4node/target/x86_64-pc-windows-gnu/release/deps" "-L" "/Users/sansan/tuya/rust4node/target/release/deps" "-L" "/Users/sansan/tuya/rust4node/target/x86_64-pc-windows-gnu/release/build/rust4node-6760a336d2281b9e/out" "-L" "/Users/sansan/tuya/rust4node/target/x86_64-pc-windows-gnu/release/build/libmimalloc-sys-504bdbf14166c2c0/out" "-L" "/Users/sansan/.cargo/registry/src/github.com-1ecc6299db9ec823/winapi-x86_64-pc-windows-gnu-0.4.0/lib" "-L" "/Users/sansan/.cargo/registry/src/github.com-1ecc6299db9ec823/windows_x86_64_gnu-0.36.1/lib" "-L" "/Users/sansan/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/x86_64-pc-windows-gnu/lib" "-lnode-x64" "-Wl,--start-group" "-Wl,--end-group" "-Wl,-Bstatic" "/Users/sansan/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/x86_64-pc-windows-gnu/lib/libcompiler_builtins-3f91c8bbaf203c3c.rlib" "-Wl,-Bdynamic" "-lwinapi_advapi32" "-lwinapi_bcrypt" "-lwinapi_cfgmgr32" "-lwinapi_credui" "-lwinapi_crypt32" "-lwinapi_cryptnet" "-lwinapi_fwpuclnt" "-lwinapi_gdi32" "-lwinapi_kernel32" "-lwinapi_msimg32" "-lwinapi_mswsock" "-lwinapi_ncrypt" "-lwinapi_ntdll" "-lwinapi_opengl32" "-lwinapi_secur32" "-lwinapi_user32" "-lwinapi_winspool" "-lwinapi_ws2_32" "-lbcrypt" "-lkernel32" "-lws2_32" "-lbcrypt" "-ladvapi32" "-luserenv" "-lkernel32" "-lgcc_eh" "-l:libpthread.a" "-lmsvcrt" "-lmingwex" "-lmingw32" "-lgcc" "-lmsvcrt" "-luser32" "-lkernel32" "-Wl,--nxcompat" "-L" "/Users/sansan/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/x86_64-pc-windows-gnu/lib" "-o" "/Users/sansan/tuya/rust4node/target/x86_64-pc-windows-gnu/release/deps/rust4node.dll" "-Wl,--gc-sections" "-shared" "-Wl,--out-implib=/Users/sansan/tuya/rust4node/target/x86_64-pc-windows-gnu/release/deps/librust4node.dll.a" "-Wl,-O1" "-nodefaultlibs" "delayimp.lib" "/DELAYLOAD:node.exe" "/Users/sansan/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/x86_64-pc-windows-gnu/lib/rsend.o"
  = note: /opt/homebrew/Cellar/mingw-w64/10.0.0_1/toolchain-x86_64/bin/x86_64-w64-mingw32-ld: cannot find delayimp.lib: No such file or directory
          /opt/homebrew/Cellar/mingw-w64/10.0.0_1/toolchain-x86_64/bin/x86_64-w64-mingw32-ld: cannot find /DELAYLOAD:node.exe: No such file or directory
          collect2: error: ld returned 1 exit status


error: could not compile `rust4node` due to previous error
Internal Error: Command failed: cargo build --release --target x86_64-pc-windows-gnu
    at checkExecSyncError (node:child_process:828:11)
    at Object.execSync (node:child_process:902:15)
    at BuildCommand.<anonymous> (/Users/sansan/tuya/rust4node/node_modules/@napi-rs/cli/scripts/index.js:14602:26)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/sansan/tuya/rust4node/node_modules/@napi-rs/cli/scripts/index.js:3423:58)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by messense** [comment]
After #1181 released, you can cross compile to Windows on macOS using [cargo-xwin](https://github.com/messense/cargo-xwin), for example

```bash
# Install LLVM and cargo-xwin
brew install llvm
cargo install cargo-xwin
# Build your project
cd your_project
CARGO=cargo-xwin yarn build --target x86_64-pc-windows-msvc
```
