### ISSUE TITLE
Support for openbsd architecture

### ISSUE THREAD

**Issue by jperocho** [napi-rs/napi-rs#1183]
Hi, 

Is there any chance of getting openbsd architecture in napi-rs?

**Comment by messense** [comment]
It's hard to support without a proper CI.

I tried to test napi-rs in `build.sr.ht` which as OpenBSD systems but it always hangs at `yarn build` step, see https://builds.sr.ht/~messense/job/758452

**Comment by jperocho** [comment]
Yes I also tried running test in OpenBsd 7.0 but its failing. I was trying to use this for NextJs in OBSD, if no test in napi and just manually add openbsd architecture, NextJs runs.
 
Thanks for trying. Will try to solve it on weekend.

**Comment by messense** [comment]
> Yes I also tried running test in OpenBsd 7.0 but its failing.

`yarn test` fails for me too on a [DigitalOcean OpenBSD droplet](https://marcocetica.com/posts/openbsd_digitalocean/), the exit code is `129` which seems indicate a fatal signal.

I'm not sure how to debug it, @Brooooooklyn any ideas?

**Comment by Brooooooklyn** [comment]
Running with lldb and the stacks like:

![图片](https://user-images.githubusercontent.com/3468483/169954635-3cbbec97-d894-42e2-9325-be1ee51486b7.png)

**Comment by snspinn** [comment]
Happen to be reading this and looks like it can be closed (as per https://github.com/nrwl/nx/issues/20931)?

**Comment by vtamara** [comment]
I confirm that nx works on OpenBSD/adJ 7.6. However napi-rs doesn't work.  I tried with the instructions of https://github.com/napi-rs/package-template

* I could run `npx napi rename -n new-name` and give the name `new-name`.
* I could run `yarn run build` that creates a file `new-name.openbsd-x64.node` 
* Running `new-name.openbsd-x64.node`  produces:
```
% ./new-name.openbsd-x64.node
zsh: segmentation fault (core dumped)  ./new-name.openbsd-x64.node
% file ./new-name.openbsd-x64.node
./new-name.openbsd-x64.node: ELF 64-bit LSB shared object, x86-64, version 1
```
Running  `yarn run test`  produces:

```
node:internal/modules/run_main:129                                              
    triggerUncaughtException(                                                   
    ^                                                                           
Error: Failed to load native binding                                            
    at Object.<anonymous> (/home/vtamara/tmp/using-napi-rs-package-template/node_modules/oxc-resolver/index.js:359:11)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Object..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Function._load (node:internal/modules/cjs/loader:1104:12)
    at cjsLoader (node:internal/modules/esm/translators:346:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:286:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:234:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
    at async Hooks.register (node:internal/modules/esm/hooks:165:26) {
  [cause]: [                                                                    
    Error: Unsupported OS: openbsd, architecture: x64             
        at requireNative (/home/vtamara/tmp/using-napi-rs-package-template/node_modules/oxc-resolver/index.js:328:21)                                           
        at Object.<anonymous> (/home/vtamara/tmp/using-napi-rs-package-template/node_modules/oxc-resolver/index.js:332:17)                                      
        at Module._compile (node:internal/modules/cjs/loader:1469:14) 
        at Object..js (node:internal/modules/cjs/loader:1548:10)                
        at Module.load (node:internal/modules/cjs/loader:1288:32)               
        at Function._load (node:internal/modules/cjs/loader:1104:12)            
        at cjsLoader (node:internal/modules/esm/translators:346:17)             
        at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:286:7) 
        at ModuleJob.run (node:internal/modules/esm/module_job:234:25)          
        at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)                                                                                  
  ]                                                                             
}                                                                               
                                                                                
Node.js v20.17.0                                                                
  ✘ __test__/index.spec.ts exited with a non-zero exit code: 1 
  ─                                                                    
```

```

**Comment by vtamara** [comment]
Trying to build napi-rs on OpenBSD/adJ 7.6 I cloned the repository and run `yarn install`, it produces:

```
➤ YN0000: · Yarn 4.6.0                                                                                                                                          
➤ YN0000: ┌ Resolution step                                                                                                                                     
➤ YN0000: └ Completed in 0s 314ms                                                                                                                               
➤ YN0000: ┌ Post-resolution validation                                                                                                                          
➤ YN0060: │ vite is listed by your project with version 6.0.6 (p0b517), which doesn't satisfy what vite-plugin-node-polyfills requests (^2.0.0 || ^3.0.0 || ^4.0
.0 || ^5.0.0).                                                                                                                                                  
➤ YN0086: │ Some peer dependencies are incorrectly met by your project; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-
prefixed code.                                                                                                                                                  
➤ YN0086: │ Some peer dependencies are incorrectly met by dependencies; run yarn explain peer-requirements for details.                                         
➤ YN0000: └ Completed                                                                                                                                           
➤ YN0000: ┌ Fetch step                                                                                                                                          
➤ YN0013: │ 1014 packages were added to the project (+ 266.33 MiB).                                                                                             
➤ YN0000: └ Completed in 28s 49ms                                                                                                                               
➤ YN0000: ┌ Link step                                                                                                                                           
➤ YN0007: │ electron@npm:33.3.0 must be built because it never has been before or the last one failed                                                           
➤ YN0007: │ esbuild@npm:0.24.2 must be built because it never has been before or the last one failed                                                            
➤ YN0007: │ nx@npm:20.3.0 [78682] must be built because it never has been before or the last one failed                          
➤ YN0007: │ esbuild@npm:0.21.5 must be built because it never has been before or the last one failed                                                            
➤ YN0007: │ msw@npm:2.7.0 [af271] must be built because it never has been before or the last one failed                          
➤ YN0007: │ edgedriver@npm:6.1.1 must be built because it never has been before or the last one failed                           
➤ YN0007: │ geckodriver@npm:5.0.0 must be built because it never has been before or the last one failed                          
➤ YN0007: │ cpu-features@npm:0.0.10 must be built because it never has been before or the last one failed                        
➤ YN0009: │ electron@npm:33.3.0 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-fb0cf4e5/build.log)
➤ YN0007: │ napi-rs@workspace:. must be built because it never has been before or the last one failed
➤ YN0007: │ ssh2@npm:1.16.0 must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 37s 137ms     
➤ YN0000: · Failed with errors in 1m 6s
```

**Comment by vtamara** [comment]
Would it be possible to remove the dependancy on electron?


electron has not been multiplatform, its supports is limited to MacOS, Windows and Linux.   It has not worked on any BSD.   On September 2023 someone sent a huge PR to add support for FreeBSD https://github.com/electron/electron/issues/3797#issuecomment-1709237608  but it was not reviewed, and the developers of electron answered 6 months after asking to rebase with main.
