### ISSUE TITLE
Specify minimum required Rust version?

### ISSUE THREAD

**Issue by vedantroy** [napi-rs/napi-rs#1184]
I tried to run the default example and got:

```
Internal Error: Command failed: cargo metadata --format-version 1
error: failed to parse manifest at `/home/vedantroy/Desktop/pdf-testing/newstack/db/Cargo.toml`

Caused by:
  feature `edition2021` is required

  consider adding `cargo-features = ["edition2021"]` to the manifest

error: failed to parse manifest at `/home/vedantroy/Desktop/pdf-testing/newstack/db/Cargo.toml`

Caused by:
  feature `edition2021` is required

  consider adding `cargo-features = ["edition2021"]` to the manifest

    at checkExecSyncError (node:child_process:828:11)
    at Object.execSync (node:child_process:902:15)
    at BuildCommand.<anonymous> (/home/vedantroy/Desktop/pdf-testing/newstack/db/node_modules/@napi-rs/cli/scripts/index.js:32071:59)
    at Generator.next (<anonymous>)
    at fulfilled (/home/vedantroy/Desktop/pdf-testing/newstack/db/node_modules/@napi-rs/cli/scripts/index.js:3495:58)
```

Running `cargo --version` gives `cargo 1.54.0-nightly (e931e4796 2021-05-24)`, which seems to have been 2021 in its release date?

I know I've run into this issue before with another tool, so I'm pretty sure I just need to update my Rust version, but it would be nice to know the minimum required Rust version.

**Comment by Nytelife26** [comment]
The README specifies [here](https://github.com/napi-rs/napi-rs#msrv) the Minimum Specified Rust Version, which is 1.57.0.

**Comment by vedantroy** [comment]
Oh, I'm very silly.
