### ISSUE TITLE
napi CLI doesn't report version correctly

### ISSUE THREAD

**Issue by Xaeroxe** [napi-rs/napi-rs#1357]
```
❯ napi version
Internal Error: Cannot find module 'C:\Users\kiese\package.json'
Require stack:
- C:\Users\kiese\AppData\Roaming\npm\node_modules\@napi-rs\cli\scripts\index.js
Require stack:
- C:\Users\kiese\AppData\Roaming\npm\node_modules\@napi-rs\cli\scripts\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at getNapiConfig (C:\Users\kiese\AppData\Roaming\npm\node_modules\@napi-rs\cli\scripts\index.js:8281:21)
    at VersionCommand.<anonymous> (C:\Users\kiese\AppData\Roaming\npm\node_modules\@napi-rs\cli\scripts\index.js:168258:44)
    at Generator.next (<anonymous>)
    at C:\Users\kiese\AppData\Roaming\npm\node_modules\@napi-rs\cli\scripts\index.js:3467:71
    at new Promise (<anonymous>)
    at __awaiter$1 (C:\Users\kiese\AppData\Roaming\npm\node_modules\@napi-rs\cli\scripts\index.js:3463:12)
```

**Comment by SASUKE40** [comment]
There is a 'DefaultPlatforms' configuration that specifies the following paths for dumping versions:
```ts
export const DefaultPlatforms: PlatformDetail[] = [
  {
    platform: 'win32',
    arch: 'x64',
    abi: 'msvc',
    platformArchABI: 'win32-x64-msvc',
    raw: 'x86_64-pc-windows-msvc',
  },
  {
    platform: 'darwin',
    arch: 'x64',
    abi: null,
    platformArchABI: 'darwin-x64',
    raw: 'x86_64-apple-darwin',
  },
  {
    platform: 'linux',
    arch: 'x64',
    abi: 'gnu',
    platformArchABI: 'linux-x64-gnu',
    raw: 'x86_64-unknown-linux-gnu',
  },
]
```
![image](https://user-images.githubusercontent.com/3114495/201142124-47b487d3-592e-419f-95d8-c84a69d9c3da.png)
