### ISSUE TITLE
Unable to generate new project without yarn

### ISSUE THREAD

**Issue by ikokostya** [napi-rs/napi-rs#1385]
New project cannot be generated using `@napi-rs/cli` tool if `yarn` package manager is not installed:

```
$ napi new
? Package name: (The name filed in your package.json) @cool/test
? Dir name: test
? Choose targets you want to support x86_64-apple-darwin, x86_64-pc-windows-msvc, x86_64-unknown-linux-gnu
? Enable github actions? No
Writing Cargo.toml
Writing .npmignore
Writing build.rs
Writing package.json
Writing src/lib.rs
Writing __test__/index.spec.mjs
Writing rustfmt.toml
Writing .gitignore
Writing .yarnrc.yml
/bin/sh: 1: yarn: not found
Internal Error: Execution failed with a non-error rejection (rejected value: undefined)
    at Cli.error (/home/kostya/.nvm/versions/node/v18.12.1/lib/node_modules/@napi-rs/cli/scripts/index.js:3254:21)
    at Cli.run (/home/kostya/.nvm/versions/node/v18.12.1/lib/node_modules/@napi-rs/cli/scripts/index.js:3070:39)
```

**Comment by JonathanWilbur** [comment]
Actually, I'm having this problem even with `yarn` installed. Almost the same problem:

```
? Package name: (The name filed in your package.json) @wildboar/x500-native
? Dir name: x500-native
? Choose targets you want to support x86_64-apple-darwin, x86_64-pc-windows-msvc, x86_64-unknown-linux-gnu, x86_64-unknown-linux-musl
? Enable github actions? Yes
Writing Cargo.toml
Writing .npmignore
Writing build.rs
Writing package.json
Writing src/lib.rs
Writing __test__/index.spec.mjs
Writing .github/workflows/CI.yml
Writing rustfmt.toml
Writing .gitignore
Writing .yarnrc.yml
Internal Error: Execution failed with a non-error rejection (rejected value: undefined)
    at Cli.error (/usr/local/lib/node_modules/@napi-rs/cli/scripts/index.js:3333:21)
    at Cli.run (/usr/local/lib/node_modules/@napi-rs/cli/scripts/index.js:3157:39)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by vijay8i** [comment]
Any update? Chiming in to report that I am having the same issue. 

```shell
napi new
? Package name: (The name filed in your package.json) @m5nv/cool
? Dir name: cool
? Choose targets you want to support aarch64-apple-darwin, x86_64-apple-darwin, x86_64-pc-windows-msvc, x86_64-unknown-linux-gnu
? Enable github actions? Yes
Writing Cargo.toml
Writing .npmignore
Writing build.rs
Writing package.json
Writing src/lib.rs
Writing __test__/index.spec.mjs
Writing .github/workflows/CI.yml
Writing .cargo/config.toml
Writing rustfmt.toml
Writing .gitignore
Writing .yarnrc.yml
/bin/sh: yarn: command not found
Internal Error: Execution failed with a non-error rejection (rejected value: undefined)
    at Cli.error (/Users/va/.nvm/versions/node/v22.1.0/lib/node_modules/@napi-rs/cli/scripts/index.js:3321:21)
    at Cli.run (/Users/va/.nvm/versions/node/v22.1.0/lib/node_modules/@napi-rs/cli/scripts/index.js:3145:39)
```

Happy to contribute if you can guide me on what needs to be fixed, where and how. Thanks.

**Comment by newproplus** [comment]
my error like 
```
Writing rustfmt.toml
Writing .gitignore
Writing .yarnrc.yml
Internal Error: Error when performing the request to https://repo.yarnpkg.com/tags; for troubleshooting help, see https://github.com/nodejs/corepack#troubleshooting
    at fetch (/home/mdkfj/apps/nodejs/node-v20.12.2-linux-x64/lib/node_modules/corepack/dist/lib/corepack.cjs:22882:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchAsJson (/home/mdkfj/apps/nodejs/node-v20.12.2-linux-x64/lib/node_modules/corepack/dist/lib/corepack.cjs:22896:20)
    at async fetchAvailableTags2 (/home/mdkfj/apps/nodejs/node-v20.12.2-linux-x64/lib/node_modules/corepack/dist/lib/corepack.cjs:22988:20)
    at async Engine.resolveDescriptor (/home/mdkfj/apps/nodejs/node-v20.12.2-linux-x64/lib/node_modules/corepack/dist/lib/corepack.cjs:23412:20)
    at async executePackageManagerRequest (/home/mdkfj/apps/nodejs/node-v20.12.2-linux-x64/lib/node_modules/corepack/dist/lib/corepack.cjs:24233:20)
    at async BinaryCommand.validateAndExecute (/home/mdkfj/apps/nodejs/node-v20.12.2-linux-x64/lib/node_modules/corepack/dist/lib/corepack.cjs:21173:22)
    at async _Cli.run (/home/mdkfj/apps/nodejs/node-v20.12.2-linux-x64/lib/node_modules/corepack/dist/lib/corepack.cjs:22148:18)
    at async Object.runMain (/home/mdkfj/apps/nodejs/node-v20.12.2-linux-x64/lib/node_modules/corepack/dist/lib/corepack.cjs:24279:12)
error Command failed.
Exit code: 1
Command: /home/mdkfj/apps/nodejs/node-v20.12.2-linux-x64/bin/node
Arguments: /home/mdkfj/apps/nodejs/node-v20.12.2-linux-x64/lib/node_modules/corepack/dist/corepack.js yarn@stable set version stable
Directory: /media/jam/648C77808C774B94/dev/_x/fivim_browser/cool
Output:

info Visit https://yarnpkg.com/en/docs/cli/policies for documentation about this command.
Internal Error: Execution failed with a non-error rejection (rejected value: undefined)
    at Cli.error (/home/mdkfj/.local/share/pnpm/global/5/.pnpm/@napi-rs+cli@2.18.4/node_modules/@napi-rs/cli/scripts/index.js:3307:21)
    at Cli.run (/home/mdkfj/.local/share/pnpm/global/5/.pnpm/@napi-rs+cli@2.18.4/node_modules/@napi-rs/cli/scripts/index.js:3131:39)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by newproplus** [comment]
My error like:

```
Writing rustfmt.toml
Writing .gitignore
Writing .yarnrc.yml
Internal Error: Error when performing the request to https://repo.yarnpkg.com/tags; for troubleshooting help, see https://github.com/nodejs/corepack#troubleshooting
    at fetch (/home/mdkfj/apps/nodejs/node-v20.12.2-linux-x64/lib/node_modules/corepack/dist/lib/corepack.cjs:22882:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchAsJson (/home/mdkfj/apps/nodejs/node-v20.12.2-linux-x64/lib/node_modules/corepack/dist/lib/corepack.cjs:22896:20)
    at async fetchAvailableTags2 (/home/mdkfj/apps/nodejs/node-v20.12.2-linux-x64/lib/node_modules/corepack/dist/lib/corepack.cjs:22988:20)
    at async Engine.resolveDescriptor (/home/mdkfj/apps/nodejs/node-v20.12.2-linux-x64/lib/node_modules/corepack/dist/lib/corepack.cjs:23412:20)
    at async executePackageManagerRequest (/home/mdkfj/apps/nodejs/node-v20.12.2-linux-x64/lib/node_modules/corepack/dist/lib/corepack.cjs:24233:20)
    at async BinaryCommand.validateAndExecute (/home/mdkfj/apps/nodejs/node-v20.12.2-linux-x64/lib/node_modules/corepack/dist/lib/corepack.cjs:21173:22)
    at async _Cli.run (/home/mdkfj/apps/nodejs/node-v20.12.2-linux-x64/lib/node_modules/corepack/dist/lib/corepack.cjs:22148:18)
    at async Object.runMain (/home/mdkfj/apps/nodejs/node-v20.12.2-linux-x64/lib/node_modules/corepack/dist/lib/corepack.cjs:24279:12)
error Command failed.
Exit code: 1
Command: /home/mdkfj/apps/nodejs/node-v20.12.2-linux-x64/bin/node
Arguments: /home/mdkfj/apps/nodejs/node-v20.12.2-linux-x64/lib/node_modules/corepack/dist/corepack.js yarn@stable set version stable
Directory: /home/mdkfj/dev/cool
Output:

info Visit https://yarnpkg.com/en/docs/cli/policies for documentation about this command.
Internal Error: Execution failed with a non-error rejection (rejected value: undefined)
    at Cli.error (/home/mdkfj/.local/share/pnpm/global/5/.pnpm/@napi-rs+cli@2.18.4/node_modules/@napi-rs/cli/scripts/index.js:3307:21)
    at Cli.run (/home/mdkfj/.local/share/pnpm/global/5/.pnpm/@napi-rs+cli@2.18.4/node_modules/@napi-rs/cli/scripts/index.js:3131:39)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
