### ISSUE TITLE
Module did not self-register

### ISSUE THREAD

**Issue by IWANABETHATGUY** [napi-rs/napi-rs#162]
internal/modules/cjs/loader.js:1188
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: Module did not self-register: '/mnt/e/rust/node-binding-comparision/napi-rs-demo/index.node'.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1188:18)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/mnt/e/rust/node-binding-comparision/napi-rs-demo/index.js:1:11)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)

**Comment by Brooooooklyn** [comment]
I guess you missed `register_module` in your code: https://github.com/napi-rs/napi-rs/blob/master/test_module/src/lib.rs#L37

You can start play with `napi-rs` in official template project: https://github.com/napi-rs/package-template

**Comment by IWANABETHATGUY** [comment]
Thanks, i think it's better to update the `napi-rs` README, the README did't mension `register_module` and other stuff in your `package-template`

**Comment by Brooooooklyn** [comment]
> i think it's better to update the napi-rs README

I have added it to README, thanks for your mention.
