### ISSUE TITLE
npm install nodejieba and  npm run build failed [Error: Cannot find module '@node-rs/jieba']

### ISSUE THREAD

**Issue by zycgit** [napi-rs/napi-rs#1621]
1. npm install nodejieba
2. npm run build
3. failed

config is 
<img width="566" alt="image" src="https://github.com/napi-rs/napi-rs/assets/4951471/a6955960-acb5-4791-8e3e-88ae2c3d6392">

yongchun.zyc@yongchunzycdeMacBook-Pro dbvisitor-doc % npm install nodejieba

up to date, audited 1198 packages in 9s

204 packages are looking for funding
  run `npm fund` for details

24 vulnerabilities (10 moderate, 14 high)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
yongchun.zyc@yongchunzycdeMacBook-Pro dbvisitor-doc % npm run build        

> dbvisitor-doc@5.2.2 build
> docusaurus build

[INFO] Website will be built for all these locales: 
- zh-cn
- en
[INFO] [zh-cn] Creating an optimized production build...
[ERROR] Unable to build website for locale zh-cn.
[ERROR] Error: Cannot find module '@node-rs/jieba'
Require stack:
- /Users/yongchun.zyc/Documents/project/hasor/split-hasor/dbvisitor/dbvisitor-doc/node_modules/lunr-languages/lunr.zh.js
- /Users/yongchun.zyc/Documents/project/hasor/split-hasor/dbvisitor/dbvisitor-doc/node_modules/@cmfcmf/docusaurus-search-local/lib/server/index.js
- /Users/yongchun.zyc/Documents/project/hasor/split-hasor/dbvisitor/dbvisitor-doc/node_modules/@docusaurus/core/lib/server/plugins/configs.js
- /Users/yongchun.zyc/Documents/project/hasor/split-hasor/dbvisitor/dbvisitor-doc/node_modules/@docusaurus/core/lib/server/plugins/init.js
- /Users/yongchun.zyc/Documents/project/hasor/split-hasor/dbvisitor/dbvisitor-doc/node_modules/@docusaurus/core/lib/server/plugins/index.js
- /Users/yongchun.zyc/Documents/project/hasor/split-hasor/dbvisitor/dbvisitor-doc/node_modules/@docusaurus/core/lib/server/index.js
- /Users/yongchun.zyc/Documents/project/hasor/split-hasor/dbvisitor/dbvisitor-doc/node_modules/@docusaurus/core/lib/commands/build.js
- /Users/yongchun.zyc/Documents/project/hasor/split-hasor/dbvisitor/dbvisitor-doc/node_modules/@docusaurus/core/lib/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
    at Function.Module._load (node:internal/modules/cjs/loader:871:27)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at /Users/yongchun.zyc/Documents/project/hasor/split-hasor/dbvisitor/dbvisitor-doc/node_modules/lunr-languages/lunr.zh.js:33:30
    at Object.<anonymous> (/Users/yongchun.zyc/Documents/project/hasor/split-hasor/dbvisitor/dbvisitor-doc/node_modules/lunr-languages/lunr.zh.js:38:2)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)

**Comment by zycgit** [comment]
Sorry that the issue was submitted in the wrong location
https://github.com/napi-rs/node-rs/issues/688
