### ISSUE TITLE
Build error for x86_64-apple-darwin

### ISSUE THREAD

**Issue by skdhg** [napi-rs/napi-rs#1688]
I am trying to make a libopus binding using napi-rs. The source code is here: [androzdev/mediaplex](https://github.com/androzdev/mediaplex). It compiles and works properly on few platforms but half of them error out (probably deps issue or something). I am a beginner in rust and I am stuck with the build errors.

[stable - x86_64-apple-darwin](https://github.com/androzdev/mediaplex/actions/runs/5777847130/job/15658455212#logs) errors out with the following error message:

```rs
error: linking with `cc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/Users/runner/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/bin:/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/xfs-dc1a0d92:/Users/runner/hostedtoolcache/node/18.17.0/x64/bin:/usr/local/lib/ruby/gems/3.0.0/bin:/usr/local/opt/ruby@3.0/bin:/usr/local/opt/pipx_bin:/Users/runner/.cargo/bin:/usr/local/opt/curl/bin:/usr/local/bin:/usr/local/sbin:/Users/runner/bin:/Users/runner/.yarn/bin:/Users/runner/Library/Android/sdk/tools:/Users/runner/Library/Android/sdk/platform-tools:/Library/Frameworks/Python.framework/Versions/Current/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/bin:/bin:/usr/sbin:/sbin:/Users/runner/.dotnet/tools:/Users/runner/.ghcup/bin:/Users/runner/hostedtoolcache/stack/2.11.1/x64" VSLANG="1033" ZERO_AR_DATE="1" "cc" "-Wl,-exported_symbols_list,/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/rustcAaRXq5/list" "-arch" "x86_64" "-m64" "/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/rustcAaRXq5/symbols.o" "/Users/runner/work/mediaplex/mediaplex/target/release/deps/mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o" "-L" "/Users/runner/work/mediaplex/mediaplex/target/release/deps" "-L" "/usr/local/Cellar/opus/1.4/lib" "-L" "/Users/runner/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "-lopus" "/Users/runner/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcompiler_builtins-3c87f4e27c528865.rlib" "-lSystem" "-lc" "-lm" "-L" "/Users/runner/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "-o" "/Users/runner/work/mediaplex/mediaplex/target/release/deps/libmediaplex.dylib" "-Wl,-dead_strip" "-dynamiclib" "-Wl,-dylib" "-nodefaultlibs"
  = note: ld: warning: dylib (/usr/local/Cellar/opus/1.4/lib/libopus.dylib) was built for newer macOS version (12.0) than being linked (10.13)
          Undefined symbols for architecture x86_64:
Internal Error: Command failed: cargo build --release
            "_napi_add_env_cleanup_hook", referenced from:
                _napi_register_module_v1 in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
    at checkExecSyncError (node:child_process:885:11)
            "_napi_call_threadsafe_function", referenced from:
    at Object.execSync (node:child_process:957:15)
                _$LT$napi..bindgen_runtime..js_values..buffer..Buffer$u20$as$u20$core..ops..drop..Drop$GT$::drop::h0f8710d17df31f4e in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
    at BuildCommand.<anonymous> (/Users/runner/work/mediaplex/mediaplex/node_modules/@napi-rs/cli/scripts/index.js:11508:30)
            "_napi_create_array_with_length", referenced from:
    at Generator.next (<anonymous>)
                napi::bindgen_runtime::js_values::object::_$LT$impl$u20$napi..js_values..object..JsObject$GT$::set::h3da76c3cba42aa6b in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
    at /Users/runner/work/mediaplex/mediaplex/node_modules/@napi-rs/cli/scripts/index.js:3512:71
            "_napi_create_buffer", referenced from:
    at new Promise (<anonymous>)
                _$LT$napi..bindgen_runtime..js_values..buffer..Buffer$u20$as$u20$napi..bindgen_runtime..js_values..ToNapiValue$GT$::to_napi_value::h0542345b0316a7d9 in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
    at __awaiter$1 (/Users/runner/work/mediaplex/mediaplex/node_modules/@napi-rs/cli/scripts/index.js:3508:12)
            "_napi_create_buffer_copy", referenced from:
    at BuildCommand.execute (/Users/runner/work/mediaplex/mediaplex/node_modules/@napi-rs/cli/scripts/index.js:11286:16)
                _$LT$napi..bindgen_runtime..js_values..buffer..Buffer$u20$as$u20$napi..bindgen_runtime..js_values..ToNapiValue$GT$::to_napi_value::h0542345b0316a7d9 in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
    at BuildCommand.validateAndExecute (/Users/runner/work/mediaplex/mediaplex/node_modules/@napi-rs/cli/scripts/index.js:2038:37)
            "_napi_create_error", referenced from:
                napi::error::JsError$LT$S$GT$::throw_into::h6dfbb5fb26449e64 in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
                napi::error::JsError$LT$S$GT$::throw_into::h88c77fd3339a2033 in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
            "_napi_create_external_buffer", referenced from:
                _$LT$napi..bindgen_runtime..js_values..buffer..Buffer$u20$as$u20$napi..bindgen_runtime..js_values..ToNapiValue$GT$::to_napi_value::h0542345b0316a7d9 in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
            "_napi_create_function", referenced from:
                mediaplex::probe::probe_js_function::h925e1f9fc0934996 in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
                mediaplex::opus::get_opus_version_js_function::h5784aa31d1ae3efa in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
                _napi_register_module_v1 in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
            "_napi_create_int32", referenced from:
                napi::bindgen_runtime::js_values::number::_$LT$impl$u20$napi..bindgen_runtime..js_values..ToNapiValue$u20$for$u20$i32$GT$::to_napi_value::h865f33fa65a3e561 in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
            "_napi_create_object", referenced from:
                mediaplex::probe::__register__enum__JsCodecType_callback__::h965bdcd3a7a6d1c6 in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
                napi::env::Env::create_object::h2060[67](https://github.com/androzdev/mediaplex/actions/runs/5777847130/job/15658455212#step:12:68)039ba2ab9c in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
                _napi_register_module_v1 in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
                napi::bindgen_runtime::module_register::napi_register_module_v1::_$u7b$$u7b$closure$u7d$$u7d$::h8e8c0004d90005ab in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
            "_napi_create_reference", referenced from:
                _$LT$napi..bindgen_runtime..js_values..buffer..Buffer$u20$as$u20$napi..bindgen_runtime..js_values..FromNapiValue$GT$::from_napi_value::h049d0b2f0e24828f in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
                _napi_register_module_v1 in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
            "_napi_create_string_utf8", referenced from:
                napi::error::JsError$LT$S$GT$::throw_into::h6dfbb5fb26449e64 in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
                napi::bindgen_runtime::js_values::string::_$LT$impl$u20$napi..bindgen_runtime..js_values..ToNapiValue$u20$for$u20$alloc..string..String$GT$::to_napi_value::h04593789af7aee92 in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
                napi::error::JsError$LT$S$GT$::throw_into::h88c77fd3339a2033 in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
                _napi_register_module_v1 in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
            "_napi_create_threadsafe_function", referenced from:
                _napi_register_module_v1 in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
            "_napi_create_uint32", referenced from:
                napi::bindgen_runtime::js_values::object::_$LT$impl$u20$napi..js_values..object..JsObject$GT$::set::hde7213a449e14013 in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
            "_napi_define_class", referenced from:
                _napi_register_module_v1 in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
            "_napi_delete_reference", referenced from:
                napi::bindgen_runtime::raw_finalize_unchecked::h84295bb89553f3e0 in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
                napi::error::JsError$LT$S$GT$::throw_into::h6dfbb5fb26449e64 in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
                core::ptr::drop_in_place$LT$napi..error..JsError$GT$::hc553e3f479f5e2a1 in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
                core::ptr::drop_in_place$LT$napi..error..Error$GT$::hc6518f054b25ebf8 in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
                mediaplex::opus::__napi_impl_helper__JsOpusEncoder__0::__napi__new::he57005fabc48183a in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
                core::ptr::drop_in_place$LT$napi..error..JsError$GT$::ha9ae8c9ba5704338 in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
                napi::error::JsError$LT$S$GT$::throw_into::h88c77fd3339a2033 in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
                ...
            "_napi_get_buffer_info", referenced from:
                _$LT$napi..bindgen_runtime..js_values..buffer..Buffer$u20$as$u20$napi..bindgen_runtime..js_values..FromNapiValue$GT$::from_napi_value::h049d0b2f0e24828f in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
            "_napi_get_cb_info", referenced from:
                napi::bindgen_runtime::callback_info::CallbackInfo$LT$_$GT$::new::h10f2a52e40109088 in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
                napi::bindgen_runtime::callback_info::CallbackInfo$LT$_$GT$::new::hb778a075135ba0cb in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
                napi::bindgen_runtime::callback_info::CallbackInfo$LT$_$GT$::new::hd58e8908cd436b27 in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
            "_napi_get_named_property", referenced from:
                _napi_register_module_v1 in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
                napi::bindgen_runtime::module_register::napi_register_module_v1::_$u7b$$u7b$closure$u7d$$u7d$::h8e8c0004d90005ab in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
            "_napi_get_reference_value", referenced from:
                napi::error::JsError$LT$S$GT$::throw_into::h6dfbb5fb26449e64 in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
                napi::error::JsError$LT$S$GT$::throw_into::h88c77fd3339a2033 in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
                _$LT$napi..bindgen_runtime..js_values..buffer..Buffer$u20$as$u20$napi..bindgen_runtime..js_values..ToNapiValue$GT$::to_napi_value::h0542345b0316a7d9 in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
            "_napi_get_undefined", referenced from:
                napi::bindgen_runtime::js_values::nil::_$LT$impl$u20$napi..bindgen_runtime..js_values..ToNapiValue$u20$for$u20$$LP$$RP$$GT$::to_napi_value::h0875a2f709e838a2 in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
            "_napi_get_value_int32", referenced from:
                napi::bindgen_runtime::js_values::number::_$LT$impl$u20$napi..bindgen_runtime..js_values..FromNapiValue$u20$for$u20$i32$GT$::from_napi_value::hab49[68](https://github.com/androzdev/mediaplex/actions/runs/5777847130/job/15658455212#step:12:69)4c0cc622f7 in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
            "_napi_reference_unref", referenced from:
                _$LT$napi..bindgen_runtime..js_values..buffer..Buffer$u20$as$u20$core..ops..drop..Drop$GT$::drop::h0f8710d17df31f4e in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
            "_napi_set_element", referenced from:
                napi::bindgen_runtime::js_values::object::_$LT$impl$u20$napi..js_values..object..JsObject$GT$::set::h3da76c3cba42aa6b in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
            "_napi_set_named_property", referenced from:
                mediaplex::probe::__register__enum__JsCodecType_callback__::h965bdcd3a7a6d1c6 in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
                mediaplex::probe::__napi__probe::hbed58757846dff75 in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
                napi::bindgen_runtime::js_values::object::_$LT$impl$u20$napi..js_values..object..JsObject$GT$::set::h0dbf231b15b36ac4 in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
                napi::bindgen_runtime::js_values::object::_$LT$impl$u20$napi..js_values..object..JsObject$GT$::set::h3da76c3cba42aa6b in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
                napi::bindgen_runtime::js_values::object::_$LT$impl$u20$napi..js_values..object..JsObject$GT$::set::hde7213a449e14013 in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
                _napi_register_module_v1 in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
                napi::bindgen_runtime::module_register::napi_register_module_v1::_$u7b$$u7b$closure$u7d$$u7d$::h8e8c0004d90005ab in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
                ...
            "_napi_throw", referenced from:
                napi::error::JsError$LT$S$GT$::throw_into::h6dfbb5fb26449e64 in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
                napi::error::JsError$LT$S$GT$::throw_into::h88c77fd3339a2033 in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
            "_napi_throw_error", referenced from:
                napi::bindgen_runtime::module_register::noop::h11920a80ed03a992 in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
            "_napi_typeof", referenced from:
                napi::bindgen_runtime::js_values::number::_$LT$impl$u20$napi..bindgen_runtime..js_values..FromNapiValue$u20$for$u20$i32$GT$::from_napi_value::hab49684c0cc622f7 in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
            "_napi_unref_threadsafe_function", referenced from:
                _napi_register_module_v1 in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
            "_napi_unwrap", referenced from:
                mediaplex::opus::__napi_impl_helper__JsOpusEncoder__0::__napi__apply_decoder_ctl::h6b3863f4fe6d33af in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
                mediaplex::opus::__napi_impl_helper__JsOpusEncoder__0::__napi__apply_encoder_ctl::h071fba622772854e in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
                mediaplex::opus::__napi_impl_helper__JsOpusEncoder__0::__napi__decode::h047db74f62092dbc in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
                mediaplex::opus::__napi_impl_helper__JsOpusEncoder__0::__napi__destroy::hbedddb9959964fdf in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
                mediaplex::opus::__napi_impl_helper__JsOpusEncoder__0::__napi__encode::ha98578c50ae731db in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
                mediaplex::opus::__napi_impl_helper__JsOpusEncoder__0::__napi__get_bitrate::h7e22f6d0ba310dd4 in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
                mediaplex::opus::__napi_impl_helper__JsOpusEncoder__0::__napi__set_bitrate::h33cfe626f96fff80 in mediaplex.mediaplex.fcea0bd772b5a3b1-cgu.0.rcgu.o
                ...
            "_napi_wrap", referenced from:
                mediaplex::opus::__napi_impl_helper__JsOpusEncoder__0::__napi__new::he5[70](https://github.com/androzdev/mediaplex/actions/runs/5777847130/job/15658455212#step:12:71)05fabc48183a in mediaplex.mediaplex.fcea0bd7[72](https://github.com/androzdev/mediaplex/actions/runs/5777847130/job/15658455212#step:12:73)b5a3b1-cgu.0.rcgu.o
          ld: symbol(s) not found for architecture x[86](https://github.com/androzdev/mediaplex/actions/runs/5777847130/job/15658455212#step:12:87)_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          

error: could not compile `mediaplex` (lib) due to previous error
Error: Process completed with exit code 1.
```

I tried digging into this but I am lost. Any help is appreciated ❤️

**Comment by Brooooooklyn** [comment]
You are missing this file https://github.com/napi-rs/package-template/blob/main/build.rs

**Comment by skdhg** [comment]
> You are missing this file https://github.com/napi-rs/package-template/blob/main/build.rs

I had that from the beginning. I forgot to update here but I got it to work by following #1005

adding the following to `.cargo/config.toml`

```toml
[target.x86_64-apple-darwin]
rustflags = ["-C", "link-args=-Wl,-undefined,dynamic_lookup"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-args=-Wl,-undefined,dynamic_lookup"]
```

thank you :tada:
