### ISSUE TITLE
pre-publish failed with  "Cannot find module 'package.json'"

### ISSUE THREAD

**Issue by ericlurker** [napi-rs/napi-rs#1855]
napi version and scripts in package.json
```
"@napi-rs/cli": "3.0.0-alpha.18",
...
"prepublishOnly": "napi pre-publish",
```

when do yarn prepublishOnly, meet error

```
$ yarn prepublishOnly
Internal Error: Cannot find module 'package.json'
Require stack:
- /Users/eric/project/rust/github/node/node_modules/@napi-rs/cli/dist/utils/misc.js
Require stack:
- /Users/eric/project/rust/github/node/node_modules/@napi-rs/cli/dist/utils/misc.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at updatePackageJson (file:///Users/eric/project/rust/github/node/node_modules/@napi-rs/cli/dist/utils/misc.js:37:17)
    at async prePublish (file:///Users/eric/project/rust/github/node/node_modules/@napi-rs/cli/dist/api/pre-publish.js:91:9)
    at async PrePublishCommand.execute (file:///Users/eric/project/rust/github/node/node_modules/@napi-rs/cli/dist/commands/pre-publish.js:6:9)
    at async PrePublishCommand.validateAndExecute (/Users/eric/project/rust/github/node/node_modules/clipanion/lib/advanced/Command.js:73:26)
    at async Cli.run (/Users/eric/project/rust/github/node/node_modules/clipanion/lib/advanced/Cli.js:223:24)
    at async Cli.runExit (/Users/eric/project/rust/github/node/node_modules/clipanion/lib/advanced/Cli.js:232:28)
(base) 

```

**Comment by Brooooooklyn** [comment]
Closed in https://github.com/napi-rs/napi-rs/pull/1860
