### ISSUE TITLE
Loading an extension errors on `x86_64-unknown-linux-musl`

### ISSUE THREAD

**Issue by Stranger6667** [napi-rs/napi-rs#2000]
Hello

Some time ago my CI builds in `css-inline` started to fail on `x86_64-unknown-linux-musl` with the following output during the `test` step:

```
Run docker run --rm --network host -v $(pwd):/build -w /build/bindings/javascript node:18-alpine yarn test

  Uncaught exception in __test__/index.spec.ts

  Error: Error relocating /build/bindings/javascript/css-inline.linux-x64-musl.node: mprotect: initial-exec TLS resolves to dynamic definition in /build/bindings/javascript/css-inline.linux-x64-musl.node

  Error: Error relocating /build/bindings/javascript/css-inline.linux-x64-musl.node: mprotect: initial-exec TLS resolves to dynamic definition in /build/bindings/javascript/css-inline.linux-x64-musl.node
      at Object.Module._extensions..node (node:internal/modules/cjs/loader:[14](https://github.com/Stranger6667/css-inline/actions/runs/7880637221/job/21502976472#step:23:15)52:18)
      at Module.load (node:internal/modules/cjs/loader:1197:32)
      at Function.Module._load (node:internal/modules/cjs/loader:1013:12)
      at Module.require (node:internal/modules/cjs/loader:1225:19)
      at require (node:internal/modules/helpers:[17](https://github.com/Stranger6667/css-inline/actions/runs/7880637221/job/21502976472#step:23:18)7:[18](https://github.com/Stranger6667/css-inline/actions/runs/7880637221/job/21502976472#step:23:19))
      at Object.<anonymous> (/build/bindings/javascript/index.js:175:31)
      at Module._compile (node:internal/modules/cjs/loader:1356:14)
      at Module._compile (/build/bindings/javascript/node_modules/pirates/lib/index.js:117:24)
      at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
      at Object.newLoader [as .js] (/build/bindings/javascript/node_modules/pirates/lib/index.js:1[21](https://github.com/Stranger6667/css-inline/actions/runs/7880637221/job/21502976472#step:23:22):7)

  ✘ __test__/index.spec.ts exited with a non-zero exit code: 1
  ─

  1 uncaught exception
```

[Example](https://github.com/Stranger6667/css-inline/actions/runs/7880637221/job/21502976472) of a failing build.

Similarly, I found that `resvg-rs` might have the same issue (see [this PR](https://github.com/yisibl/resvg-js/pull/306)). 

I am not sure about the direction to fix this, but my assumption is that it is likely a misconfiguration on my side which is not compatible with the latest Docker image for MUSL, or something on the napi-rs side :( Any suggestions are appreciated

**Comment by Brooooooklyn** [comment]
@Stranger6667 you must enable `local_dynamic_tls` on Linux https://github.com/yisibl/resvg-js/pull/306/files#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R30

**Comment by Stranger6667** [comment]
Thank you!
