### ISSUE TITLE
Running Napi new to create project error

### ISSUE THREAD

**Issue by qidasheng369** [napi-rs/napi-rs#2070]
Computer environment: MacBook Pro 13-inch, 2019, Two Thunderbolt 3 ports 1.4 GHz 四核Intel Core i5
macOS: 14.1.2 (23B92)
pnpm version:  9.0.6
node version: v22.0.0
yanr version: 3.6.0

```
❯ napi new
? Package name: (The name filed in your package.json) rs-native
? Dir name: rs-native
? Choose targets you want to support x86_64-apple-darwin,
x86_64-pc-windows-msvc, x86_64-unknown-linux-gnu
? Enable github actions? Yes
Writing Cargo.toml
Writing .npmignore
Writing build.rs
Writing package.json
Writing src/lib.rs
Writing __test__/index.spec.mjs
Writing .github/workflows/CI.yml
Writing .cargo/config.toml
Writing rustfmt.toml
Writing .gitignore
Writing .yarnrc.yml
Unknown Syntax Error: Unsupported option name ("--yarn-path").

$ yarn set version [--only-if-needed] <version>
Internal Error: Execution failed with a non-error rejection (rejected value: undefined)
    at Cli.error (/Users/zhouzhou/lib/pnpm/global/5/.pnpm/@napi-rs+cli@2.18.2/node_modules/@napi-rs/cli/scripts/index.js:3321:21)
```

**Comment by newproplus** [comment]
My error like:

```
Writing rustfmt.toml
Writing .gitignore
Writing .yarnrc.yml
Internal Error: Error when performing the request to https://repo.yarnpkg.com/tags; for troubleshooting help, see https://github.com/nodejs/corepack#troubleshooting
    at fetch (/home/mdkfj/apps/nodejs/node-v20.12.2-linux-x64/lib/node_modules/corepack/dist/lib/corepack.cjs:22882:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchAsJson (/home/mdkfj/apps/nodejs/node-v20.12.2-linux-x64/lib/node_modules/corepack/dist/lib/corepack.cjs:22896:20)
    at async fetchAvailableTags2 (/home/mdkfj/apps/nodejs/node-v20.12.2-linux-x64/lib/node_modules/corepack/dist/lib/corepack.cjs:22988:20)
    at async Engine.resolveDescriptor (/home/mdkfj/apps/nodejs/node-v20.12.2-linux-x64/lib/node_modules/corepack/dist/lib/corepack.cjs:23412:20)
    at async executePackageManagerRequest (/home/mdkfj/apps/nodejs/node-v20.12.2-linux-x64/lib/node_modules/corepack/dist/lib/corepack.cjs:24233:20)
    at async BinaryCommand.validateAndExecute (/home/mdkfj/apps/nodejs/node-v20.12.2-linux-x64/lib/node_modules/corepack/dist/lib/corepack.cjs:21173:22)
    at async _Cli.run (/home/mdkfj/apps/nodejs/node-v20.12.2-linux-x64/lib/node_modules/corepack/dist/lib/corepack.cjs:22148:18)
    at async Object.runMain (/home/mdkfj/apps/nodejs/node-v20.12.2-linux-x64/lib/node_modules/corepack/dist/lib/corepack.cjs:24279:12)
error Command failed.
Exit code: 1
Command: /home/mdkfj/apps/nodejs/node-v20.12.2-linux-x64/bin/node
Arguments: /home/mdkfj/apps/nodejs/node-v20.12.2-linux-x64/lib/node_modules/corepack/dist/corepack.js yarn@stable set version stable
Directory: /home/mdkfj/dev/cool
Output:

info Visit https://yarnpkg.com/en/docs/cli/policies for documentation about this command.
Internal Error: Execution failed with a non-error rejection (rejected value: undefined)
    at Cli.error (/home/mdkfj/.local/share/pnpm/global/5/.pnpm/@napi-rs+cli@2.18.4/node_modules/@napi-rs/cli/scripts/index.js:3307:21)
    at Cli.run (/home/mdkfj/.local/share/pnpm/global/5/.pnpm/@napi-rs+cli@2.18.4/node_modules/@napi-rs/cli/scripts/index.js:3131:39)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
