### ISSUE TITLE
Usage with Astro

### ISSUE THREAD

**Issue by viperML** [napi-rs/napi-rs#2206]
I have trouble getting napi to work with astro. I believe the problem lies in the importing logic, CommonJS vs ES modules and Vite.

Related: https://github.com/napi-rs/napi-rs/issues/1429, https://github.com/orgs/napi-rs/discussions/1437

```
21.47.14 [ERROR] [vite] x Build failed in 519ms
src/layouts/Layout.astro (8:9): "sum" is not exported by "napi-astro-rs/index.js", imported by "src/layouts/Layout.astro".
file: /home/ayats/Documents/napi-astro/src/layouts/Layout.astro:8:9

 6: const { title } = Astro.props;
 7:
 8: import { sum } from "napi-astro-rs";
             ^
 9: const result = sum(1,2);
10: ---

  Stack trace:
    at getRollupError (file:///home/ayats/Documents/napi-astro/node_modules/rollup/dist/es/shared/parseAst.js:392:41)
    at Module.error (file:///home/ayats/Documents/napi-astro/node_modules/rollup/dist/es/shared/node-entry.js:13958:16)
    at ModuleScope.findVariable (file:///home/ayats/Documents/napi-astro/node_modules/rollup/dist/es/shared/node-entry.js:12110:39)
    at FunctionBodyScope.findVariable (file:///home/ayats/Documents/napi-astro/node_modules/rollup/dist/es/shared/node-entry.js:7465:38)
    at CallExpression.bind (file:///home/ayats/Documents/napi-astro/node_modules/rollup/dist/es/shared/node-entry.js:4808:23)
```

I have put a minimal reproducer here: https://github.com/viperML/napi-astro

**Comment by viperML** [comment]
Importing the module with a simple JS file outside Astro/Vite seems to work:

```
$ cat test.js
import { sum } from "napi-astro-rs";

console.log(sum(1,2));

$ node test.js
3
```

**Comment by hi-ogawa** [comment]
I'm not too sure about the build error, but the issue on dev is because Vite SSR doesn't support CJS for workspace dependency (or "non external" dependency in general) https://vitejs.dev/guide/ssr.html#ssr-externals.

In your reproduction, `napi-astro-rs` is your workspace package, so Vite SSR tries to evaluate `napi-astro-rs/index.js` on its own way, but `require` is not supported in this context. Workaround is to explicitly set `ssr.external: ["napi-astro-rs"]`, so the import is handled by NodeJs (or whatever base runtime). 

I verified the following astro config make it work both for dev and build:

```js
import { defineConfig } from 'astro/config';

// https://astro.build/config
export default defineConfig({
  vite: {
    ssr: {
      external: ["napi-astro-rs"]
    }
  }
});
```

**Comment by viperML** [comment]
Thank you, that seems to work. I have to this flies over my head, but I hope other people might find this solution in the future.

**Comment by viperML** [comment]
Of couse, I ran into a problem just after marking this as solved:

Trying to call my napi function from a rehype plugin, results in the following different error:

```
19.08.26 [vite] Error when evaluating SSR module /neohome-rs/index.js:
|- ReferenceError: require is not defined
    at /home/ayats/Documents/neohome/neohome-rs/index.js:7:38
    at instantiateModule (file:///home/ayats/Documents/neohome/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:56237:
```

This is for [https://github.com/viperML/neohome/tree/260caec7efac2645f1e7b04d8c6ac22ba4a59f1c](viperML/neohome@260caec), but I can put a minimal reporducer if needed.

The napi code is loaded here:

https://github.com/viperML/neohome/blob/260caec7efac2645f1e7b04d8c6ac22ba4a59f1c/src/rehype.ts#L11

Which is loaded as a rehype plugin here:

https://github.com/viperML/neohome/blob/260caec7efac2645f1e7b04d8c6ac22ba4a59f1c/astro.config.ts#L48

**Comment by hi-ogawa** [comment]
Haven't look into your project, but I'm thinking this can be reproduced with any cjs workspace package (aka. linked dependency) in general. If you can reproduce that without napi-rs, then you should report that on astro side.

**Comment by hi-ogawa** [comment]
I think I got a simple reproduction without napi-rs, so I reported an issue on astro https://github.com/withastro/astro/issues/11621

**Comment by hi-ogawa** [comment]
I haven't tested but you can probably use `createRequire` to avoid Vite intercepting import.

```ts
// src/rehype.ts
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
const { highlight } = require("neohome-rs");
```

**Comment by zhiyuanzmj** [comment]
Try `--esm` option:
```sh
napi build --platform --release --esm
```
