### ISSUE TITLE
Unexpected panic from napi side for specific inputs

### ISSUE THREAD

**Issue by kdy1** [napi-rs/napi-rs#2313]
This caused an issue for SWC. See: https://github.com/swc-project/swc/issues/8868

# Input code

```js
  swc.minifySync('\u001a\u0000', {
    mangle: true,
    module: true
  })
```

The stack trace reports the `#[napi]` line below.

```rust
#[napi]
pub fn minify_sync(
    code: Buffer,
    opts: Buffer,
    extras: NapiMinifyExtra,
) -> napi::Result<TransformOutput> {
```

# Steps to reproduce

1. `git checkout https://github.com/kdy1/swc.git -b issue-8868`
2. `yarn`
3. `yarn build:dev`
4. `yarn test`

# Log:

```
 PASS   unit tests  __tests__/import_test.js
 PASS   unit tests  __tests__/transform/issue_5325_test.mjs
 PASS   unit tests  __tests__/minify/name_cache.test.mjs
 PASS   unit tests  __tests__/script_test.js
thread '<unnamed>' panicked at /Users/kdy1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/napi-2.16.8/src/error.rs:324:1:
called `Result::unwrap()` on an `Err` value: NulError(66, [32, 32, 27, 91, 51, 49, 109, 120, 27, 91, 48, 109, 32, 85, 110, 101, 120, 112, 101, 99, 116, 101, 100, 32, 99, 104, 97, 114, 97, 99, 116, 101, 114, 32, 39, 92, 117, 123, 49, 97, 125, 39, 10, 32, 32, 32, 44, 45, 45, 45, 45, 10, 32, 27, 91, 50, 109, 49, 27, 91, 48, 109, 32, 124, 32, 26, 0, 10, 32, 32, 32, 58, 32, 27, 91, 51, 53, 59, 49, 109, 94, 27, 91, 48, 109, 10, 32, 32, 32, 96, 45, 45, 45, 45, 10, 10, 10, 67, 97, 117, 115, 101, 100, 32, 98, 121, 58, 10, 32, 32, 32, 32, 48, 58, 32, 102, 97, 105, 108, 101, 100, 32, 116, 111, 32, 112, 97, 114, 115, 101, 32, 105, 110, 112, 117, 116, 32, 102, 105, 108, 101, 10, 32, 32, 32, 32, 49, 58, 32, 83, 121, 110, 116, 97, 120, 32, 69, 114, 114, 111, 114])
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 PASS   unit tests  __tests__/transform/hidden_jest.js
 PASS   unit tests  __tests__/transform/issue_8491_test.mjs
 PASS   unit tests  __tests__/parse/api_test.js
 PASS   unit tests  __tests__/transform/experimental.mjs
 PASS   unit tests  __tests__/transform/issue834_test.js
thread '<unnamed>' panicked at core/src/panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
std::backtrace_rs::backtrace::libunwind::trace::h12643cfe09de4bdb
                               at /rustc/55a22d2a63334e0faff0202b72a31ce832b56125/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:        0x340a0e5c8 - std::backtrace_rs::backtrace::trace_unsynchronized::h219b74e29e080a35
                               at /rustc/55a22d2a63334e0faff0202b72a31ce832b56125/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x340a0e5c8 - std::sys::backtrace::_print_fmt::h7a084e55e5259736
                               at /rustc/55a22d2a63334e0faff0202b72a31ce832b56125/library/std/src/sys/backtrace.rs:66:9
   3:        0x340a0e5c8 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h3516d3727e4fe664
                               at /rustc/55a22d2a63334e0faff0202b72a31ce832b56125/library/std/src/sys/backtrace.rs:39:26
rt::Argument::fmt::ha33f6690e4ce79e0::
                               at /rustc/55a22d2a63334e0faff0202b72a31ce832b56125/library/core/src/fmt/rt.rs:177:76
   5:        0x340a2f94c - core::fmt::write::h3cf25e6890d6884f
                               at /rustc/55a22d2a63334e0faff0202b72a31ce832b56125/library/core/src/fmt/mod.rs:1186:21
   6:        0x340a0ad10 - std::io::Write::write_fmt::h371ae990c0f80aae
                              at /rustc/55a22d2a63334e0faff0202b72a31ce832b56125/library/std/src/io/mod.rs:1839:15
backtrace::BacktraceLock::print::h6e94cfd2d824d621
                               at /rustc/55a22d2a63334e0faff0202b72a31ce832b56125/library/std/src/sys/backtrace.rs:42:9
::default_hook::{{closure}}::h08f2daea39d90bc3
                               at /rustc/55a22d2a63334e0faff0202b72a31ce832b56125/library/std/src/panicking.rs:268:22
     0x340a0f02c - std::panicking::default_hook::he290e37d54206f0f
                               at /rustc/55a22d2a63334e0faff0202b72a31ce832b56125/library/std/src/panicking.rs:295:9
  10:        0x340a0f99c - std::panicking::rust_panic_with_hook::he9e7a691abc6490c
              at /rustc/55a22d2a63334e0faff0202b72a31ce832b56125/library/std/src/panicking.rs:801:13
  11:        0x340a0f628 - std::panicking::begin_panic_handler::{{closure}}::h76e8e9b8127ee308
                               at /rustc/55a22d2a63334e0faff0202b72a31ce832b56125/library/std/src/panicking.rs:667:13
  12:        0x340a0ea8c - std::sys::backtrace::__rust_end_short_backtrace::h96d8ed392cde8e6b
                               at /rustc/55a22d2a63334e0faff0202b72a31ce832b56125/library/std/src/sys/backtrace.rs:170:18
  13:        0x340a0f308 - rust_begin_unwind
                        at /rustc/55a22d2a63334e0faff0202b72a31ce832b56125/library/std/src/panicking.rs:665:5
::hc5bc3609f47eecdb3cbf4 - core::panicking::panic_nounwind_fmt::runtime
                               at /rustc/55a22d2a63334e0faff0202b72a31ce832b56125/library/core/src/panicking.rs:112:18
  15:        0x340b3cbf4 - core::panicking::panic_nounwind_fmt::h54d719431190a0b7
                               at /rustc/55a22d2a63334e0faff0202b72a31ce832b56125/library/core/src/panicking.rs:122:5
  16:        0x340b3cc6c - core::panicking::panic_nounwind::haff73e8f1609db96
                               at /rustc/55a22d2a63334e0faff0202b72a31ce832b56125/library/core/src/panicking.rs:221:5
17:        0x340b3cde4 - core::panicking::panic_cannot_unwind::h9e5a31d7b1180074
                               at /rustc/55a22d2a63334e0faff0202b72a31ce832b56125/library/core/src/panicking.rs:310:5
  0x33cabf474 - binding_core_node::minify::__napi__minify_sync::hb9619736e2f6a6f8
                               at /Users/kdy1/projects/s/chores/bindings/binding_core_node/src/minify.rs:116:1
thread caused non-unwinding panic. aborting.
```

**Comment by CPunisher** [comment]
This is caused by https://github.com/napi-rs/napi-rs/blob/383b5d023cc0f14c2de51b8611e9745e2bfa26bb/crates/napi/src/error.rs#L266C49-L266C55, where the error message that swc returns contains interior nul byte "\0".

🤔 Maybe we can filter the interior nul byte in swc or in napi.
