### ISSUE TITLE
FreeBSD & i686 Windows MSVC builds fail out-of-the-box on GitHub CI

### ISSUE THREAD

**Issue by Nickersoft** [napi-rs/napi-rs#2350]
Hey folks,

I just started a new NAPI project, where the only modification I made to the CI was swapping out Yarn for PNPM. I'm noticing 2 failures, one for i686 and one for FreeBSD. The i686 issue seems to relate to peer dependencies while FreeBSD seems to be a lower-level error.

**i686 Failure:**

```
Error: Cannot find module @rollup/rollup-win32-ia32-msvc. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
    at requireWithFriendlyError (D:\a\odict-node\odict-node\node_modules\.pnpm\rollup@4.25.0\node_modules\rollup\dist\native.js:63:9)
    at Object.<anonymous> (D:\a\odict-node\odict-node\node_modules\.pnpm\rollup@4.25.0\node_modules\rollup\dist\native.js:72:76)
    ... 3 lines matching cause stack trace ...
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at cjsLoader (node:internal/modules/esm/translators:346:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:286:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:234:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:473:24) {
  [cause]: Error: Cannot find module '@rollup/rollup-win32-ia32-msvc'
  Require stack:
  - D:\a\odict-node\odict-node\node_modules\.pnpm\rollup@4.25.0\node_modules\rollup\dist\native.js
      at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
      at Module._load (node:internal/modules/cjs/loader:1051:27)
      at Module.require (node:internal/modules/cjs/loader:1311:19)
      at require (node:internal/modules/helpers:179:18)
      at requireWithFriendlyError (D:\a\odict-node\odict-node\node_modules\.pnpm\rollup@4.25.0\node_modules\rollup\dist\native.js:45:10)
      at Object.<anonymous> (D:\a\odict-node\odict-node\node_modules\.pnpm\rollup@4.25.0\node_modules\rollup\dist\native.js:72:76)
      at Module._compile (node:internal/modules/cjs/loader:1469:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
      at Module.load (node:internal/modules/cjs/loader:1288:32)
      at Module._load (node:internal/modules/cjs/loader:1104:12) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      'D:\\a\\odict-node\\odict-node\\node_modules\\.pnpm\\rollup@4.25.0\\node_modules\\rollup\\dist\\native.js'
    ]
  }
}
```

**FreeBSD error:**

```
Message from node20-20.17.0:

--
Note: If you need npm (Node Package Manager), please install www/npm.
=====
Message from python311-3.11.10:

--
Note that some standard Python modules are provided as separate ports
as they require additional dependencies. They are available as:

py311-gdbm       databases/py-gdbm@py311
py311-sqlite3    databases/py-sqlite3@py311
py311-tkinter    x11-toolkits/py-tkinter@py311
ld-elf.so.1: /usr/local/bin/node: Undefined symbol "_ZNSt3__122__libcpp_verbose_abortEPKcz"
```

The full actions run is [here](https://github.com/TheOpenDictionary/odict-node/actions/runs/11759479805). My (slightly) modified CI config is [here](https://github.com/TheOpenDictionary/odict-node/blob/main/.github/workflows/CI.yml).

Has anyone else run into these issues? Has it come up before?

**Comment by Brooooooklyn** [comment]
@Nickersoft thanks for your reporting! I'm aware of this issue. Upgrade components in the published CLI is a complex job, I'm planning to download the project template from the GitHub project directly in the https://github.com/napi-rs/package-template or https://github.com/napi-rs/package-template-pnpm

**Comment by Nickersoft** [comment]
Thanks for the reply @Brooooooklyn! Is this issue the cause of both failures, or just the first one? The FreeBSD error seemed more system-level. Is there any workaround right now? I was planning to just disable these platforms on my project for now.
