### ISSUE TITLE
Failed to get constructor of class

### ISSUE THREAD

**Issue by mischnic** [napi-rs/napi-rs#970]
Some of the fixed related to https://github.com/napi-rs/napi-rs/issues/933#issuecomment-1000857979 don't work when renaming the class with `js_name = `:

```rust
#[napi(js_name = "Assets")]
pub struct JsAssets {}

#[napi]
impl JsAssets {
  #[napi(constructor)]
  pub fn new() -> Self {
    JsAssets {}
  }

  #[napi]
  pub fn get(&mut self, id: u32) -> Option<JsAsset> {
    Some(JsAsset {})
  }
}

#[napi(js_name = "Asset")]
struct JsAsset {}

#[napi]
impl JsAsset {
  pub fn new() -> Self {
    Self {}
  }

  #[napi(getter)]
  pub fn get_filePath(&self) -> u32 {
    return 1;
  }
}
```

```js
const {Assets} = require('./native');
let assets = new Assets();
let a = assets.get(0);
console.log(a);
```

throws

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: NulError(41, [70, 97, 105, 108, 101, 100, 32, 116, 111, 32, 103, 101, 116, 32, 99, 111, 110, 115, 116, 114, 117, 99, 116, 111, 114, 32, 111, 102, 32, 99, 108, 97, 115, 115, 32, 96, 65, 115, 115, 101, 116, 0, 96])', /Users/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/napi-2.0.2/src/error.rs:248:1
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   2: core::result::unwrap_failed
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1616:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1298:23
   4: napi::error::JsError::into_value
             at /Users/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/napi-2.0.2/src/error.rs:175:22
   5: napi::error::JsError::throw_into
             at /Users/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/napi-2.0.2/src/error.rs:204:24
   6: parcel_structs::assets::__napi_impl_helper__JsAssets__0::__napi__get::{{closure}}
             at ./src/assets.rs:158:1
   7: core::result::Result<T,E>::unwrap_or_else
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1082:23
   8: parcel_structs::assets::__napi_impl_helper__JsAssets__0::__napi__get
             at ./src/assets.rs:158:1
   9: __ZN6v8impl12_GLOBAL__N_123FunctionCallbackWrapper6InvokeERKN2v820FunctionCallbackInfoINS2_5ValueEEE
  10: __ZN2v88internal25FunctionCallbackArguments4CallENS0_15CallHandlerInfoE
  11: __ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE
  12: __ZN2v88internal21Builtin_HandleApiCallEiPmPNS0_7IsolateE
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
[1]    36940 abort      RUST_BACKTRACE=1 node x.js
```

This is what the error message says:
```
> [70, 97, 105, 108, 101, 100, 32, 116, 111, 32, 103, 101, 116, 32, 99, 111, 110, 115, 116, 114, 117, 99, 116, 111, 114, 32, 111, 102, 32, 99, 108, 97, 115, 115, 32, 96, 65, 115, 115, 101, 116, 0, 96].map(f => String.fromCharCode(f)).join("")
'Failed to get constructor of class `Asset\x00`'
```

**Comment by Brooooooklyn** [comment]
@mischnic 

```rust
#[napi(js_name = "Asset")]
struct JsAsset {}

#[napi]
impl JsAsset {
  pub fn new() -> Self {
    Self {}
  }

  #[napi(getter)]
  pub fn get_filePath(&self) -> u32 {
    return 1;
  }
}
```

missing `#[napi(constructor)]` on `pub fn new()`

**Comment by mischnic** [comment]
Sorry, my code sample didn't really represent my actual problem: the constructor parameters aren't compatible with napi values. So this doesn't compile

```rust
#[napi(js_name = "Assets")]
pub struct JsAssets {
  inner: Rc<RefCell<Vec<u8>>>,
}

#[napi]
impl JsAssets {
  #[napi(constructor)]
  pub fn new() -> Self {
    Self {
      inner: Rc::new(RefCell::new(Vec::new())),
    }
  }

  #[napi]
  pub fn get(&self) -> JsAsset {
    JsAsset {
      inner: Rc::clone(&self.inner),
    }
  }
}

#[napi]
struct JsAsset {
  inner: Rc<RefCell<Vec<u8>>>,
}

#[napi]
impl JsAsset {
  #[napi(constructor)]
  pub fn new(inner: Rc<RefCell<Vec<u8>>>) -> Self {
    Self { inner }
  }
}
```

**Comment by Brooooooklyn** [comment]
Yes. So the problem becomes to you don't have a constructor for `struct`...
